.PHONY: clean All

All:
	@echo "----------Building project:[ Assignment2 - Debug ]----------"
	@$(MAKE) -f  "Assignment2.mk"
clean:
	@echo "----------Cleaning project:[ Assignment2 - Debug ]----------"
	@$(MAKE) -f  "Assignment2.mk" clean
