.PHONY: clean All

All:
	@echo "----------Building project:[ Project3 - Debug ]----------"
	@$(MAKE) -f  "Project3.mk"
clean:
	@echo "----------Cleaning project:[ Project3 - Debug ]----------"
	@$(MAKE) -f  "Project3.mk" clean
