.PHONY: clean All

All:
	@echo "----------Building project:[ Project1 - Debug ]----------"
	@$(MAKE) -f  "Project1.mk"
clean:
	@echo "----------Cleaning project:[ Project1 - Debug ]----------"
	@$(MAKE) -f  "Project1.mk" clean
